spring:
  application:
   
     spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Admin@123
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employee_management_system
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true